apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: 17200082/k8s-auth:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
