apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-container
          image: 17200082/k8s-tasks:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: "tasks"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
