apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: 17200082/k8s-users:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: auth-container
          image: 17200082/k8s-auth:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
